/**
 * Shot-tied world + copy. Walk shots set x1/z1 so bodies travel.
 * Y comes from terrain/bridge.
 */
export const CHAPTERS = {
  logo: {
    n: '00',
    kicker: 'STILL LISTED',
    title: 'THE PHOTO THAT OUTLIVED THE OWNERS',
    line: 'Dawn again. The sign did not come down. Nobody asked it to.',
    hour: 6.35,
    weather: 'clear',
    mario: { x: -0.7, z: 16.4, yaw: Math.PI, moving: false, gesture: 'wave' },
    luigi: { x: 1.4, z: 16.8, yaw: Math.PI, moving: false, gesture: 'idle' },
  },
  approach: {
    n: '01',
    kicker: 'CURB APPEAL',
    title: 'THEY PAVED NOTHING',
    line: 'A dirt suggestion of a driveway. The castle pretends this is charming.',
    hour: 8.4,
    weather: 'clear',
    mario: { x: -0.5, z: 16.0, x1: -0.4, z1: 10.5, yaw: Math.PI, moving: true, gesture: 'walk' },
    luigi: { x: 1.3, z: 17.4, x1: 1.2, z1: 12.2, yaw: Math.PI, moving: true, gesture: 'walk' },
  },
  plumber: {
    n: '02',
    kicker: 'HOST A',
    title: 'HE SMILES FOR THE EASEMENT',
    line: 'The wrench is not for the pipes. It is for something he cannot name.',
    hour: 9.6,
    weather: 'clear',
    mario: { x: 0.15, z: 15.0, yaw: 2.6, moving: false, gesture: 'present' },
    luigi: { x: 2.4, z: 17.2, yaw: 3.3, moving: false, gesture: 'measure' },
  },
  bridge: {
    n: '03',
    kicker: 'WATER RIGHTS',
    title: 'THE MOAT OUTLASTED THE FAMILY',
    line: 'Chains sag on purpose. The water does not care who holds the deed.',
    hour: 11.1,
    weather: 'clear',
    mario: { x: -1.6, z: 6.0, x1: -1.5, z1: 1.2, yaw: Math.PI, moving: true, gesture: 'walk' },
    luigi: { x: 1.1, z: -14.0, yaw: 0.4, moving: false, gesture: 'measure' },
  },
  rose: {
    n: '04',
    kicker: 'ORIGINAL GLASS',
    title: 'SHE IS STILL IN THE WINDOW',
    line: 'Lead time: 1985. The portrait did not agree to be a feature.',
    hour: 12.1,
    weather: 'clear',
    mario: { x: -2.8, z: -17.6, yaw: 0.25, moving: false, gesture: 'point' },
    luigi: { x: 2.2, z: -16.4, yaw: -0.35, moving: false, gesture: 'shrug' },
  },
  nave: {
    n: '05',
    kicker: 'FOYER',
    title: 'THEY FORGOT TO BUILD A HOUSE',
    line: 'Hollow on purpose. You buy the volume. The volume does not buy you back.',
    hour: 13.4,
    weather: 'overcast',
    mario: { x: 0.0, z: -26.0, yaw: Math.PI, moving: false, gesture: 'present' },
    luigi: { x: 1.6, z: -31.6, yaw: 0.35, moving: false, gesture: 'measure' },
  },
  garden: {
    n: '06',
    kicker: 'LANDSCAPE ALLOWANCE',
    title: 'MATURE PLANTINGS',
    line: 'Forty-eight flowers. One height. The brochure said English garden. The earth said no.',
    hour: 15.2,
    weather: 'overcast',
    mario: { x: 6.2, z: 13.4, yaw: 0.9, moving: false, gesture: 'present' },
    luigi: { x: 8.0, z: 11.6, yaw: -0.4, moving: false, gesture: 'kneel' },
  },
  ascent: {
    n: '07',
    kicker: 'FOURTH FLOOR',
    title: 'NO ONE TAKES THE STAIRS',
    line: 'Four towers. One gold pin. The elevator was the first thing they cut.',
    hour: 17.5,
    weather: 'overcast',
    mario: { x: -4.0, z: -21.5, yaw: 0.7, moving: false, gesture: 'point' },
    luigi: { x: 3.4, z: -20.4, yaw: -0.55, moving: false, gesture: 'shrug' },
  },
  storm: {
    n: '08',
    kicker: 'INSPECTION DAY',
    title: 'THE HOUSE INSPECTS YOU',
    line: 'Mario calls it character. Luigi brought a second opinion and lost it in the rain.',
    hour: 18.7,
    weather: 'storm',
    mario: { x: -8.4, z: -6.0, x1: -5.6, z1: -10.5, yaw: 0.9, moving: true, gesture: 'walk' },
    luigi: { x: 7.2, z: -5.0, x1: 5.0, z1: -9.2, yaw: -0.5, moving: true, gesture: 'shiver' },
  },
  circuit: {
    n: '09',
    kicker: 'LOT LINES',
    title: 'THE BOUNDARY IS GRIEF',
    line: 'The surveyor quit. The drone finished. The lawyer billed the horizon.',
    hour: 19.5,
    weather: 'rain',
    mario: { x: -1.0, z: 8.4, yaw: 0.2, moving: false, gesture: 'idle' },
    luigi: { x: 1.4, z: 9.2, yaw: 0.1, moving: false, gesture: 'idle' },
  },
  night: {
    n: '10',
    kicker: 'TWILIGHT SHOWING',
    title: 'NOBODY CAME',
    line: 'Fireflies work the open house. Luigi brought a lantern for guests that do not exist.',
    hour: 21.15,
    weather: 'clear',
    mario: { x: -1.8, z: 13.0, yaw: 0.45, moving: false, gesture: 'wave' },
    luigi: { x: 1.4, z: 14.1, yaw: -0.3, moving: false, gesture: 'idle', lantern: true },
  },
  endcard: {
    n: '11',
    kicker: 'THE REVEAL',
    title: 'SOLD TO NO ONE',
    line: 'They closed the loop instead. The moat kept the earnest money.',
    hour: 7.15,
    weather: 'clear',
    mario: { x: -0.9, z: 16.3, yaw: 0.2, moving: false, gesture: 'shrug' },
    luigi: { x: 1.3, z: 16.5, yaw: -0.2, moving: false, gesture: 'shrug' },
  },
};

export function chapterFor(id) {
  return CHAPTERS[id] || CHAPTERS.logo;
}
