/**
 * Shot-tied world + copy. Poses snap on a cut if the jump is large
 * (main.js). Y comes from terrain/bridge.
 */
export const CHAPTERS = {
  logo: {
    n: '00',
    kicker: 'SEASON PREMIERE',
    title: 'THE LISTING PHOTO',
    line: 'Dawn. Wide. Nobody has signed the disclosure yet.',
    hour: 6.35,
    weather: 'clear',
    mario: { x: -0.7, z: 16.4, yaw: Math.PI, moving: false, gesture: 'wave' },
    luigi: { x: 1.4, z: 16.8, yaw: Math.PI, moving: false, gesture: 'idle' },
  },
  approach: {
    n: '01',
    kicker: 'CURB APPEAL',
    title: 'THE DRIVEWAY IS A THEORY',
    line: 'Dirt path, optimistic grass budget, castle acting casual.',
    hour: 8.4,
    weather: 'clear',
    mario: { x: -0.5, z: 13.2, yaw: Math.PI, moving: true, gesture: 'walk' },
    luigi: { x: 1.3, z: 14.8, yaw: Math.PI, moving: true, gesture: 'walk' },
  },
  plumber: {
    n: '02',
    kicker: 'HOST A',
    title: 'HE BROUGHT A WRENCH TO A SHOWING',
    line: 'Not for the pipes. For morale.',
    hour: 9.6,
    weather: 'clear',
    mario: { x: 0.15, z: 15.0, yaw: 2.6, moving: false, gesture: 'present' },
    luigi: { x: 2.4, z: 17.2, yaw: 3.3, moving: false, gesture: 'measure' },
  },
  bridge: {
    n: '03',
    kicker: 'WATER RIGHTS',
    title: 'WHO PAYS THE MOAT BILL',
    line: 'The chains sag on purpose. Luigi has filed this under "character."',
    hour: 11.1,
    weather: 'clear',
    mario: { x: -1.6, z: 3.4, yaw: Math.PI, moving: true, gesture: 'walk' },
    luigi: { x: 1.1, z: -14.0, yaw: 0.4, moving: false, gesture: 'measure' },
  },
  rose: {
    n: '04',
    kicker: 'ORIGINAL GLASS',
    title: 'THE WINDOW THAT CAME WITH A PERSON',
    line: 'Lead time: 1985. Replacement: do not ask.',
    hour: 12.1,
    weather: 'clear',
    mario: { x: -2.8, z: -17.6, yaw: 0.25, moving: false, gesture: 'point' },
    luigi: { x: 2.2, z: -16.4, yaw: -0.35, moving: false, gesture: 'shrug' },
  },
  nave: {
    n: '05',
    kicker: 'FOYER',
    title: 'THERE IS NO FOYER',
    line: 'You walk in and the house is already the whole house.',
    hour: 13.4,
    weather: 'overcast',
    mario: { x: 0.0, z: -26.0, yaw: Math.PI, moving: false, gesture: 'present' },
    luigi: { x: 1.6, z: -31.6, yaw: 0.35, moving: false, gesture: 'measure' },
  },
  well: {
    n: '06',
    kicker: 'UNPERMITTED VOLUME',
    title: 'THE KEEP IS A SUGGESTION',
    line: 'Hollow on purpose. The square footage is spiritual.',
    hour: 16.2,
    weather: 'overcast',
    mario: { x: -1.5, z: -33.6, yaw: 0.15, moving: false, gesture: 'cheer' },
    luigi: { x: 1.6, z: -32.8, yaw: -0.2, moving: false, gesture: 'point' },
  },
  ascent: {
    n: '07',
    kicker: 'FOURTH FLOOR',
    title: 'THE STAIRS WERE CUT FOR BUDGET',
    line: 'Four towers. One gold pin. Elevator: denied.',
    hour: 17.5,
    weather: 'overcast',
    mario: { x: -4.0, z: -21.5, yaw: 0.7, moving: false, gesture: 'point' },
    luigi: { x: 3.4, z: -20.4, yaw: -0.55, moving: false, gesture: 'shrug' },
  },
  storm: {
    n: '08',
    kicker: 'INSPECTION DAY',
    title: 'THE ATTIC IS A WEATHER SYSTEM',
    line: 'Mario calls it ambience. Luigi brought a second opinion: leave.',
    hour: 18.7,
    weather: 'storm',
    mario: { x: -7.2, z: -8.5, yaw: 0.9, moving: true, gesture: 'walk' },
    luigi: { x: 6.2, z: -7.2, yaw: -0.5, moving: true, gesture: 'shiver' },
  },
  circuit: {
    n: '09',
    kicker: 'LOT LINES',
    title: 'THE PROPERTY LINE IS THE HORIZON',
    line: 'Surveyor quit. Drone finished the job. Lawyer is drafting a poem.',
    hour: 19.5,
    weather: 'rain',
    mario: { x: -1.0, z: 8.4, yaw: 0.2, moving: false, gesture: 'idle' },
    luigi: { x: 1.4, z: 9.2, yaw: 0.1, moving: false, gesture: 'idle' },
  },
  night: {
    n: '10',
    kicker: 'TWILIGHT SHOWING',
    title: 'FIREFLIES ARE NOT RECESSED LIGHTING',
    line: 'Luigi packed a lantern. The listing photos will be warmer than the truth.',
    hour: 21.15,
    weather: 'clear',
    mario: { x: -1.8, z: 13.0, yaw: 0.45, moving: false, gesture: 'wave' },
    luigi: { x: 1.4, z: 14.1, yaw: -0.3, moving: false, gesture: 'idle', lantern: true },
  },
  welcome: {
    n: '11',
    kicker: 'OPEN HOUSE',
    title: 'THE LOOP IS THE CLOSING',
    line: 'Walk up. Walk in. Walk out. Sign nothing. Repeat at dawn.',
    hour: 6.7,
    weather: 'clear',
    mario: { x: -0.8, z: 16.2, yaw: Math.PI, moving: false, gesture: 'present' },
    luigi: { x: 1.2, z: 16.6, yaw: Math.PI, moving: false, gesture: 'wave' },
  },
  endcard: {
    n: '12',
    kicker: 'THE REVEAL',
    title: 'SOLD TO THE BROTHERS',
    line: 'They bought the joke. The joke came with a moat.',
    hour: 7.15,
    weather: 'clear',
    mario: { x: -0.9, z: 16.3, yaw: 0.2, moving: false, gesture: 'cheer' },
    luigi: { x: 1.3, z: 16.5, yaw: -0.2, moving: false, gesture: 'cheer' },
  },
};

export function chapterFor(id) {
  return CHAPTERS[id] || CHAPTERS.logo;
}
