/**
 * Shot-tied world + copy. Hour and weather are targets the loop eases toward.
 * Plumber poses are world XZ + yaw + gesture. Y comes from terrain/bridge.
 */
export const CHAPTERS = {
  logo: {
    n: '00',
    kicker: 'HGTV ADJACENT',
    title: 'PROPERTY PLUMBERS',
    line: 'Two brothers. One keep. Zero permits. Welcome to the listing.',
    tag: 'NEW LISTING',
    featured: 'both',
    hour: 6.4,
    weather: 'clear',
    mario: { x: 0.0, z: 16.2, yaw: Math.PI, moving: false, gesture: 'wave' },
    luigi: { x: 1.8, z: 17.1, yaw: Math.PI, moving: false, gesture: 'shrug' },
  },
  approach: {
    n: '01',
    kicker: 'CURB APPEAL',
    title: 'SHE HAS GOOD BONES',
    line: 'Mario loves the path. Luigi is already measuring the path.',
    tag: 'GOOD BONES\u2122',
    featured: 'mario',
    hour: 8.2,
    weather: 'clear',
    mario: { x: 0.0, z: 14.6, yaw: Math.PI, moving: true, gesture: 'walk' },
    luigi: { x: 1.7, z: 17.4, yaw: Math.PI, moving: true, gesture: 'measure' },
  },
  plumber: {
    n: '02',
    kicker: 'MEET THE TALENT',
    title: 'MARIO \u00b7 DEMO & DESIGN',
    line: 'Mustache: load-bearing. Confidence: over budget. Wrench: emotional support.',
    tag: 'HOST A',
    featured: 'mario',
    hour: 9.5,
    weather: 'clear',
    mario: { x: 0.0, z: 15.2, yaw: Math.PI * 0.92, moving: true, gesture: 'present' },
    luigi: { x: 2.2, z: 17.8, yaw: Math.PI, moving: false, gesture: 'idle' },
  },
  bridge: {
    n: '03',
    kicker: 'STRUCTURAL CONCERN',
    title: 'LUIGI \u00b7 THE MOAT TOUR',
    line: 'Chains sag on purpose. That is not a sentence you want from your inspector.',
    tag: 'WATER FEATURE',
    featured: 'luigi',
    hour: 11.0,
    weather: 'clear',
    mario: { x: -1.4, z: 4.2, yaw: Math.PI, moving: true, gesture: 'wave' },
    luigi: { x: 1.15, z: -14.2, yaw: Math.PI * 0.15, moving: false, gesture: 'measure' },
  },
  rose: {
    n: '04',
    kicker: 'STATEMENT PIECE',
    title: 'THE LOFTED ROSE',
    line: 'Pink glass, dual surface, unofficial luxury preset. Do not ask about the lead time.',
    tag: 'ORIGINAL 1985',
    featured: 'mario',
    hour: 12.0,
    weather: 'clear',
    mario: { x: -2.4, z: -18.4, yaw: 0.35, moving: false, gesture: 'point' },
    luigi: { x: 1.6, z: -17.2, yaw: -0.2, moving: false, gesture: 'shrug' },
  },
  nave: {
    n: '05',
    kicker: 'OPEN CONCEPT KEEP',
    title: 'WAIT. IT IS HOLLOW.',
    line: 'Luigi brought a tape. The architects brought vibes. Nobody brought a floor plan.',
    tag: 'OPEN CONCEPT',
    featured: 'luigi',
    hour: 13.2,
    weather: 'overcast',
    mario: { x: 0.0, z: -26.2, yaw: Math.PI, moving: false, gesture: 'present' },
    luigi: { x: 1.4, z: -32.4, yaw: 0.4, moving: false, gesture: 'measure' },
  },
  well: {
    n: '06',
    kicker: 'NATURAL LIGHT',
    title: 'LOOK UP, SHE SAID',
    line: 'Dust motes performing mandated sparkle. Luigi is pricing the chandelier.',
    tag: 'SOARING CEILINGS',
    featured: 'both',
    hour: 16.4,
    weather: 'overcast',
    mario: { x: -1.3, z: -34.0, yaw: 0.2, moving: false, gesture: 'cheer' },
    luigi: { x: 1.5, z: -33.2, yaw: -0.15, moving: false, gesture: 'point' },
  },
  ascent: {
    n: '07',
    kicker: 'VERTICAL SQUARE FOOTAGE',
    title: 'FOUR TOWERS, NO ELEVATOR',
    line: 'If you can still see the gold pin, congratulations, your offer is in.',
    tag: '+4 SPIRES',
    featured: 'both',
    hour: 17.6,
    weather: 'overcast',
    mario: { x: -3.2, z: -22.0, yaw: 0.6, moving: false, gesture: 'point' },
    luigi: { x: 2.8, z: -21.2, yaw: -0.5, moving: false, gesture: 'shrug' },
  },
  storm: {
    n: '08',
    kicker: 'THE INSPECTION',
    title: 'WEATHER ABUSE INCLUDED',
    line: 'Mario: character. Luigi: we are going to die. The keep: smiling.',
    tag: 'AS-IS SALE',
    featured: 'mario',
    hour: 18.6,
    weather: 'storm',
    mario: { x: -8.0, z: -10.0, yaw: 0.8, moving: true, gesture: 'cheer' },
    luigi: { x: 6.5, z: -8.4, yaw: -0.4, moving: true, gesture: 'shiver' },
  },
  circuit: {
    n: '09',
    kicker: 'LOT LINES',
    title: 'AND THIS IS ALL YOURS',
    line: 'Recommended viewing distance was three seconds ago. Bring a drone and a lawyer.',
    tag: 'ACREAGE: YES',
    featured: 'both',
    hour: 19.4,
    weather: 'rain',
    mario: { x: -1.2, z: 8.0, yaw: 0.2, moving: true, gesture: 'walk' },
    luigi: { x: 1.6, z: 9.4, yaw: 0.15, moving: true, gesture: 'walk' },
  },
  night: {
    n: '10',
    kicker: 'TWILIGHT SHOWING',
    title: 'LUIGI BROUGHT A LANTERN',
    line: "Fireflies. Nature's bloom pass. Luigi would like the listing taken down now.",
    tag: 'MOOD LIGHTING',
    featured: 'luigi',
    hour: 21.2,
    weather: 'clear',
    mario: { x: -1.6, z: 13.2, yaw: 0.4, moving: false, gesture: 'wave' },
    luigi: { x: 1.5, z: 14.2, yaw: -0.25, moving: false, gesture: 'idle', lantern: true },
  },
  welcome: {
    n: '11',
    kicker: 'THE WALK-UP',
    title: 'SHALL WE GO INSIDE?',
    line: 'They will walk up. Then they will walk back. The loop is the closing.',
    tag: 'COME ON IN',
    featured: 'both',
    hour: 6.8,
    weather: 'clear',
    mario: { x: -0.7, z: 16.4, yaw: Math.PI, moving: false, gesture: 'present' },
    luigi: { x: 1.1, z: 16.8, yaw: Math.PI, moving: false, gesture: 'wave' },
  },
  endcard: {
    n: '12',
    kicker: 'THE REVEAL',
    title: 'SOLD. TO THE PLUMBERS.',
    line: 'Graphics: yes. Atmosphere: yes. Jumping: still not in the budget.',
    tag: 'SOLD',
    featured: 'both',
    hour: 7.2,
    weather: 'clear',
    mario: { x: -0.8, z: 16.4, yaw: 0.15, moving: false, gesture: 'cheer' },
    luigi: { x: 1.2, z: 16.6, yaw: -0.15, moving: false, gesture: 'cheer' },
  },
};

export function chapterFor(id) {
  return CHAPTERS[id] || CHAPTERS.logo;
}
