/**
 * Shot-tied world + copy. Hour and weather are targets the loop eases toward.
 * Mario poses are world XZ + yaw; Y comes from terrain/bridge.
 */
export const CHAPTERS = {
  logo: {
    n: '00',
    kicker: 'ULTRA PRESET',
    title: 'CASTLE GROUNDS',
    line: 'A 120-second flyby. No controller. No mercy. One plumber.',
    hour: 6.4,
    weather: 'clear',
    mario: { x: 0, z: 16.2, yaw: Math.PI, moving: false },
  },
  approach: {
    n: '01',
    kicker: 'GRAPHICS TEST',
    title: 'THE KINGDOM, LOAD-BEARING',
    line: 'Establishing shot. Grass budget: optimistic. Path: dirt.',
    hour: 8.2,
    weather: 'clear',
    mario: { x: 0, z: 16.0, yaw: Math.PI, moving: true },
  },
  plumber: {
    n: '02',
    kicker: 'CHARACTER THROUGHPUT',
    title: 'SUBJECT: ONE (1) PLUMBER',
    line: 'Mustache tessellation: adequate. Jump button: not shipped.',
    hour: 9.5,
    weather: 'clear',
    mario: { x: 0, z: 15.2, yaw: Math.PI, moving: true },
  },
  bridge: {
    n: '03',
    kicker: 'GEOMETRY STRESS',
    title: 'TESSELLATED MOAT',
    line: 'Water is wet. Chains sag on purpose. This is a pass.',
    hour: 11.0,
    weather: 'clear',
    mario: { x: 0, z: 2.0, yaw: Math.PI, moving: true },
  },
  rose: {
    n: '04',
    kicker: 'TRANSMISSION BUDGET',
    title: 'THE LOFTED ROSE',
    line: 'Pink glass, dual surface, unofficial luxury preset.',
    hour: 12.0,
    weather: 'clear',
    mario: { x: 0, z: -18.0, yaw: Math.PI, moving: true },
  },
  nave: {
    n: '05',
    kicker: 'INTERIOR VOLUME',
    title: 'HOLLOW KEEP',
    line: 'The architects are not taking questions.',
    hour: 13.2,
    weather: 'overcast',
    mario: { x: 0, z: -26.4, yaw: Math.PI, moving: false },
  },
  well: {
    n: '06',
    kicker: 'PARTICLE UNION',
    title: 'LOOK UP',
    line: 'Dust motes performing mandated sparkle. Do not applaud.',
    hour: 16.4,
    weather: 'overcast',
    mario: { x: 0, z: -26.4, yaw: 0, moving: false },
  },
  ascent: {
    n: '07',
    kicker: 'VERTICAL FLEX',
    title: 'SPIRE THROUGHPUT',
    line: 'If you can still see the gold pin, your GPU likes you.',
    hour: 17.6,
    weather: 'overcast',
    mario: { x: 0, z: -24.0, yaw: 0, moving: false },
  },
  storm: {
    n: '08',
    kicker: 'WEATHER ABUSE',
    title: 'PERSONAL RAIN',
    line: 'Cloud coverage: spite. Draw calls: also spite.',
    hour: 18.6,
    weather: 'storm',
    mario: { x: 0, z: -10.0, yaw: 0, moving: true },
  },
  circuit: {
    n: '09',
    kicker: 'ORBITAL SCORE',
    title: 'LEAVING DRAW DISTANCE',
    line: 'Recommended viewing distance was three seconds ago.',
    hour: 19.4,
    weather: 'rain',
    mario: { x: 0, z: 8.0, yaw: 0, moving: true },
  },
  night: {
    n: '10',
    kicker: 'UNPAID OVERTIME',
    title: 'NIGHT SHIFT',
    line: 'Fireflies. Nature\'s bloom pass. Overtime is not approved.',
    hour: 21.2,
    weather: 'clear',
    mario: { x: 0, z: 14.0, yaw: Math.PI * 0.15, moving: false },
  },
  welcome: {
    n: '11',
    kicker: 'CALL TO ADVENTURE',
    title: 'HE WALKED UP',
    line: 'Then he will walk back. The loop is the product.',
    hour: 6.8,
    weather: 'clear',
    mario: { x: 0, z: 16.4, yaw: Math.PI, moving: false },
  },
  endcard: {
    n: '12',
    kicker: 'RESULTS',
    title: 'FINAL SCORE: YES',
    line: 'Graphics: yes. Atmosphere: yes. Jumping: still no.',
    hour: 7.2,
    weather: 'clear',
    mario: { x: 0, z: 16.4, yaw: Math.PI, moving: false },
  },
};

export function chapterFor(id) {
  return CHAPTERS[id] || CHAPTERS.logo;
}
